import Foundation
import PDFKit

struct InvoiceResult: Identifiable {
    let id = UUID()
    let filename: String
    let source: String   // "Holded" | "CommonGround" | "Unknown"
    let total: Double
}

enum IncomingScanner {

    static func scan(folder: URL) -> [InvoiceResult] {
        let files = (try? FileManager.default.contentsOfDirectory(
            at: folder, includingPropertiesForKeys: nil
        )) ?? []
        return files
            .filter { $0.pathExtension.lowercased() == "pdf" }
            .compactMap { parse(url: $0) }
            .sorted { $0.filename < $1.filename }
    }

    static func parse(url: URL) -> InvoiceResult? {
        guard let doc = PDFDocument(url: url) else { return nil }

        var text = (0..<doc.pageCount)
            .compactMap { doc.page(at: $0)?.string }
            .joined(separator: "\n")

        if text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
           let docText = doc.string {
            text = docText
        }

        // CommonGround PDFs are generated by a renderer that writes character runs
        // right-to-left in the content stream. PDFKit reads them raw, producing
        // reversed text ("latoT" instead of "Total", "89.86€" instead of "€68.98").
        // Fix: when reversed markers are present but normal ones aren't, flip each line.
        text = normalizeText(text)

        guard let total = extractTotal(from: text) else { return nil }
        return InvoiceResult(
            filename: url.lastPathComponent,
            source: detectSource(from: text),
            total: total
        )
    }

    // MARK: - Private helpers

    private static func normalizeText(_ text: String) -> String {
        let lower = text.lowercased()
        // "latot" = "Total" reversed. If it appears without "total", text is reversed.
        guard lower.contains("latot"), !lower.contains("total") else { return text }
        return text.components(separatedBy: .newlines)
            .map { String($0.reversed()) }
            .joined(separator: "\n")
    }

    private static func extractTotal(from text: String) -> Double? {
        // Find every decimal amount (X.XX or X,XX) in the document and return the max.
        //
        // Why max() instead of label-matching:
        // - Holded: PDFKit extracts table columns separately, placing "TOTAL 529,50€"
        //   and "424,50€" rows far apart with no reliable "total" label bridge.
        // - CommonGround: after line-reversal the amounts are readable but label
        //   proximity is not guaranteed.
        // The grand total is always >= every line-item amount and subtotal by definition.
        guard let regex = try? NSRegularExpression(pattern: #"(\d+[.,]\d{2})"#) else { return nil }
        let range = NSRange(text.startIndex..., in: text)
        let amounts = regex.matches(in: text, range: range).compactMap { match -> Double? in
            guard let r = Range(match.range(at: 1), in: text) else { return nil }
            return Double(String(text[r]).replacingOccurrences(of: ",", with: "."))
        }
        return amounts.max()
    }

    private static func detectSource(from text: String) -> String {
        if text.contains("FACTURA") || text.contains("BASE IMPONIBLE") { return "Holded" }
        if text.contains("Invoice #WS") || text.contains("Online Order") { return "CommonGround" }
        return "Unknown"
    }
}
