import Foundation
import PDFKit

struct InvoiceResult: Identifiable {
    let id = UUID()
    let filename: String
    let source: String   // "Holded" | "CommonGround" | "Unknown"
    let total: Double
    let date: Date?
}

enum IncomingScanner {

    static func scan(folder: URL) -> [InvoiceResult] {
        let files = (try? FileManager.default.contentsOfDirectory(
            at: folder, includingPropertiesForKeys: nil
        )) ?? []
        return files
            .filter { $0.pathExtension.lowercased() == "pdf" }
            .compactMap { parse(url: $0) }
            .sorted { $0.filename < $1.filename }
    }

    static func parse(url: URL) -> InvoiceResult? {
        guard let doc = PDFDocument(url: url) else { return nil }

        var text = (0..<doc.pageCount)
            .compactMap { doc.page(at: $0)?.string }
            .joined(separator: "\n")

        if text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
           let docText = doc.string {
            text = docText
        }

        // CommonGround PDFs are generated by a renderer that writes character runs
        // right-to-left in the content stream. PDFKit reads them raw, producing
        // reversed text ("latoT" instead of "Total", "89.86€" instead of "€68.98").
        // Fix: when reversed markers are present but normal ones aren't, flip each line.
        text = normalizeText(text)

        guard let total = extractTotal(from: text) else { return nil }
        let date = (try? FileManager.default.attributesOfItem(atPath: url.path))?[.modificationDate] as? Date
        return InvoiceResult(
            filename: url.lastPathComponent,
            source: detectSource(from: text),
            total: total,
            date: date
        )
    }

    // MARK: - Private helpers

    private static func normalizeText(_ text: String) -> String {
        let lower = text.lowercased()
        // "latot" = "Total" reversed. If it appears without "total", text is reversed.
        guard lower.contains("latot"), !lower.contains("total") else { return text }
        return text.components(separatedBy: .newlines)
            .map { String($0.reversed()) }
            .joined(separator: "\n")
    }

    private static func extractTotal(from text: String) -> Double? {
        // Find every decimal amount in the document and return the max.
        //
        // Why max() instead of label-matching:
        // - Holded: PDFKit extracts table columns separately, so "TOTAL" and its amount
        //   are too far apart to bridge reliably.
        // - CommonGround: after line-reversal amounts are readable but label proximity
        //   is not guaranteed.
        // The grand total is always >= every line-item amount and subtotal by definition.
        //
        // Pattern handles European thousands-separator format (3.467,50) and simple
        // decimals (529,50). Structure: leading digits, optional sep+3digit groups
        // (thousands), then sep+2digits (cents). This prevents "3.467,50" from being
        // split into "3.46" + "7,50" by the old \d+[.,]\d{2} pattern.
        guard let regex = try? NSRegularExpression(
            pattern: #"(\d+(?:[.,]\d{3})*[.,]\d{2})"#
        ) else { return nil }
        let range = NSRange(text.startIndex..., in: text)
        let amounts = regex.matches(in: text, range: range).compactMap { match -> Double? in
            guard let r = Range(match.range(at: 1), in: text) else { return nil }
            return parseAmount(String(text[r]))
        }
        return amounts.max()
    }

    // Converts a matched amount string to Double regardless of separator convention.
    // Detects format by which separator appears last: comma-last = European (12.171,20),
    // dot-last = US/simple (12,171.20 or 529.50), comma-only = European simple (529,50).
    private static func parseAmount(_ s: String) -> Double? {
        let lastComma = s.lastIndex(of: ",")
        let lastDot   = s.lastIndex(of: ".")
        if let c = lastComma, let d = lastDot {
            return c > d
                ? Double(s.replacingOccurrences(of: ".", with: "").replacingOccurrences(of: ",", with: "."))
                : Double(s.replacingOccurrences(of: ",", with: ""))
        } else if lastComma != nil {
            return Double(s.replacingOccurrences(of: ",", with: "."))
        } else {
            return Double(s)
        }
    }

    private static func detectSource(from text: String) -> String {
        if text.contains("FACTURA") || text.contains("BASE IMPONIBLE") { return "Holded" }
        if text.contains("Invoice #WS") || text.contains("Online Order") { return "CommonGround" }
        return "Unknown"
    }
}
